### ISSUE TITLE
php module intl is missing for TYPO3 9

### ISSUE THREAD

**Issue by juergen-venne** [ArminVieweg/ubuntu-xenial64-lamp#1]
I recently tested with TYPO3 9 and during the installation process of TYPO3 the message about the intl module appears. After proceeding the TYPO3 backend fall with an error message. I guess that PHP 7.2 module is mandatory.
Is it possible to add that module to the default php 7.2 installation?
Kind regards
Jürgen

**Comment by ArminVieweg** [comment]
Hey Jürgen, sure I'll add it by default for next box release :)

**Comment by ArminVieweg** [comment]
I've added phpX.X-intl for all installed PHP versions (since box version 1.8.1)
