### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by linxpinx** [ArminVieweg/ubuntu-xenial64-lamp#2]
Hi Armin,

`vagrant up `

gives me 

```
URL: ["https://atlas.hashicorp.com/ArminVieweg/ubuntu-xenial64-lamp"]
Error: The requested URL returned error: 404 Not Found
```
Did you move ArminVieweg/ubuntu-xenial64-lamp to another Location?

**Comment by ArminVieweg** [comment]
Hi. No I didn't. 
https://app.vagrantup.com/ArminVieweg/boxes/ubuntu-xenial64-lamp

But I think that they did some movement in the past and "app.vagrantup.com" is the old one.

This is how it works for me:


```
> vagrant box add ArminVieweg/ubuntu-xenial64-lamp                                                                       
==> box: Loading metadata for box 'ArminVieweg/ubuntu-xenial64-lamp'                                                     
    box: URL: https://vagrantcloud.com/ArminVieweg/ubuntu-xenial64-lamp                                                  
==> box: Adding box 'ArminVieweg/ubuntu-xenial64-lamp' (v1.8.6) for provider: virtualbox                                 
    box: Downloading: https://vagrantcloud.com/ArminVieweg/boxes/ubuntu-xenial64-lamp/versions/1.8.6/providers/virtualbox.box          
```                                                                                                           
Maybe it helps to update vagrant itself.

**Comment by linxpinx** [comment]
Hi Armin,

on my machine vagrant tries to load from atlas.hashicorp.com. Your Box is on app.vagrantup.com. Soooo I try 
`vagrant box add https://app.vagrantup.com/ArminVieweg/boxes/ubuntu-xenial64-lamp`
and this seems to work.
